apiVersion: apps/v2
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: uddhavt89/python-calculator:v2
        ports:
        - containerPort: 5000
